version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=db  # Nom du service SQL Server dans ce cas
      - DB_NAME= GRIM_EMECEF_2025
      - DB_USER=USER
      - DB_PASSWORD=ECOLE
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TonMotDePasseStrong
    ports:
      - "1433:1433"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
